### PR TITLE
Allow users to add and remove usernames

### PR DESCRIPTION
**Pull request by maiquynhtruong**
This is for issue #6 
We can add and remove usernames dynamically. However, changes are not saved. The username array is in usernames.js. I was thinking of modifying that file but could not find a way to do that with Javascript. I hope you could review this PR and let me know how I can further improve it.

### CODE REVIEW

**Comment by mubaris** [comment]
This PR looks clean. I have few suggestions.

* Use different colors for Language selection and Username selections. Preferably Orange color I used for to show repository details
* Reduce the font of both Language & Username selctions

Then I will merge this. Thank you :+1:

**Comment by raulvillares** [comment]
@maiquynhtruong To save changes one possibility is store the usernames with localStorage just like the access token.

Though to get real persistence some database system should be used. @mubaris I don't know if that beyond the project's scope...

**Comment by mubaris** [comment]
@raulvillares @maiquynhtruong We can use `LocalStorage` for now. But I wanted it to be complete client side web application. So now Databases for now.

**Comment by mubaris** [comment]
@maiquynhtruong I'm merging this commit for now. I will put another issue to change UI for Selections.

**Comment by maiquynhtruong** [comment]
I couldn't get to touch a laptop until now. I'll see what I can do for the UI and make another PR

**Pull request merged**
