### PR TITLE
Fixes issue #18

### PR DESCRIPTION
**Pull request by raulvillares**
Language selector changes to a html select element.

### CODE REVIEW

**Comment by mubaris** [comment]
You don't have to generate Language Selector. Make a list of langauges predefined then, when the user select one of them isolate projects of that languages only.

[List of all languages recognized by Github](https://github.com/kamranahmedse/githunt/blob/master/githunt.html#L33-L340)

Refer the above list and project to implement this.

Fix all the **Codacy, Code Climate** issues.

Follow the following [JS Style Guide](https://github.com/kamranahmedse/githunt/blob/master/githunt.html#L33-L340) 

**Please define all the variables using `var` at the top of the document. Only `let` and `const` will be allowed in the middle of the document.**

**Comment by mubaris** [comment]
I'm closing this now. Send another PR.

**Comment by raulvillares** [comment]
Hi,

I'm working on your comments. But the link for JS Style Guide is not right. Can you post the right one, please?

Thanks!

**Comment by mubaris** [comment]
[JS Style Guide](https://github.com/airbnb/javascript)

Here you go.

**Pull request closed without merging**
